name: push-to-ghcr
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and push docker images (public)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ inputs.container_registry }}/${{ inputs.container_registry_directory }}/${{ matrix.name }}
          flavor: |
            latest=true
          tags: |
            type=raw,value=latest

      - name: docker login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
